### ISSUE TITLE
Error configuring maven annotation processor path

### ISSUE THREAD

**Issue by cvgaviao** [toolisticon/SPI-Annotation-Processor#13]
When I follow the instructions on readme I got the following error in Eclipse IDE:
`cvc-complex-type.3.2.2: Attribute 'combine.self' is not allowed to appear in element 'configuration'. ` 

I've discovered that the right place to put it is in the `<annotationProcessorPaths>` tag. Also, if you are inheriting from a parent pom already containing other processors paths, what have worked for me was to use `combine.children="append"` instead `combine.self="append"`:
```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler.version}</version>
          <configuration>
            <release>16</release>
            <annotationProcessorPaths combine.children="append">
              <path>
                <groupId>io.toolisticon.spiap</groupId>
                <artifactId>spiap-processor</artifactId>
                <version>CURRENT_VERSION</version>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>

```

**Comment by tobiasstamann** [comment]
Thanks for the hint.

It seems to be either combine.self="override" or combine.children="append"

I guess for an invalid configuration it falls back to combine.self="merge", for that reason it still seems to work in most cases.

I will update the README file.
