### ISSUE TITLE
@Service is hiding Spring @Service annotation

### ISSUE THREAD

**Issue by fishermans** [toolisticon/SPI-Annotation-Processor#16]
Hi,

@Service should be renamed to @SpiService to avoid conflicts with Spring @Service annotation. To remain downward compatible, an additional annotation would also be conceivable. In this context I would also rename @Services to @SpiServices or provide it additionally.

Unfortunately, @AnnotatonWrapper does not allow you to define interfaces for the wrappers. This would prevent the duplication of the ServiceProvider class.

THX

**Comment by tobiasstamann** [comment]
Hi, I will try to provide a second annotation and follow the name schema you have suggested.

A workaround would be to use the fully qualified name when you use the annotation. 
This would allow you to use both annotation types in parallel.

like:
@io.toolisticon.spiap.api.Service(Processor.class)

**Comment by fishermans** [comment]
Yes, I know. Thanks. 

It's not me who should be able to create services. That's, why I asked you to add an alternative annotation.
I sent a PR #15 yesterday to also support @SpiServiceLocators. If you are going to spend some time, it would be great if you could also add support for multiple ServiceLocators in the same package.

**Comment by tobiasstamann** [comment]
I will take a look at your PR later.

Additionally i will add the possibility to provide Custom interfaces to Annotation Wrappers in APTK.
That change is likely to be a no brainer and eases to processing of alias annotation types.

**Comment by fishermans** [comment]
Sound great. Thank you so much for your time!!!

**Comment by tobiasstamann** [comment]
Thanks for the PR. I have accepted it and did the release 0.9.2.

About the alias annotations. I have prepared a changed for the APTK library to support interfaces.
I should be able to provide both legacy Service and SpiService annotation processing in a few days.

**Comment by tobiasstamann** [comment]
Hi, 

created  a solution for this in the following [feature-branch](https://github.com/toolisticon/SPI-Annotation-Processor/tree/feature/alias_for_annotations)

Please check if it suits your needs.

**Comment by fishermans** [comment]
Hi Tobias,
I will give it a try later today.
BR
Tiemo

**Comment by fishermans** [comment]
Looks good to me. 

In the meantime, I had created the two annotations myself and modified the processor. I was now able to switch to the new implementation without any problems.

**Comment by tobiasstamann** [comment]
Thanks for your feedback.

AdditionallyI will move the old Services/Service annotations to a legacy-api module which depends on the api module. 
By doing that you wont have any issues with your IDE anymore as well.

On the long term i am going to get rid of them. I don't thing that it will hurt a lot of people, since this library isn't that popular.

Hope you liked working with the annotation processing and testing libraries.

**Comment by fishermans** [comment]
Good point. Maybe, it makes sense to mark the legacy annotations as deprecated with a small hint to migrate to the new ones?

BTW: I implemented your processor into our company wide build pipeline. So, please keep going on maintaining it. :-)

**Comment by tobiasstamann** [comment]
I have already marked them as deprecated :)

I will do a new release containing the changes later today.

**Comment by tobiasstamann** [comment]
Release 0.10.0 is out now containing the changed annotation names.
Old annotations are now contained in spiap-legacy-api module.
