### ISSUE TITLE
ServiceLocator produced by Version 0.10.0 requires Service annotation

### ISSUE THREAD

**Issue by fishermans** [toolisticon/SPI-Annotation-Processor#20]
Hi Tobias,

Unfortunately, I have to be annoying again. 

In the new version 0.10.0 there are still references to the old service annotations inside the tpl file of the ServiceLocator. So, if you don't include the legacy artifact, the compiler is caught an exception and fails.

**Comment by tobiasstamann** [comment]
Hi, 

have you encounter such an exception? Usually The annotations shouldn't be needed.
There is the GeneratedServiceLocatorFileTest File in the integrationTest/withoutSpiapApi, which is testing the usage of the ServiceLocator without the spiap-api / spiap-legacy-api dependency present.

The extraction of the configuration from annotations is encapsulated in a try/catch NoClassDefError block, if the annotations are not present, configuration will solely be done via properties,(which should be equal to annotation based config in most cases.)

BR

Tobias

**Comment by tobiasstamann** [comment]
I should definitely switch order of reading the annotations first the SpiService, the the legacy annotations.
But this shouldn't be a big deal, because in most cases the active configuration will be pulled from properties anyways.

**Comment by tobiasstamann** [comment]
I will remove the old annotations and only support the new ones, then it's safe to use & compile again.
My previous post were true just about runtime not compilation...

**Comment by tobiasstamann** [comment]
Release 0.11.0 without the old Service/Services annotation is out now.
I guess i should have just renamed them in the first place ;)
